ALTER USER 'root'@'%' IDENTIFIED BY 'root_pwd_123456';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY 'app_mysql_12345';
GRANT ALL PRIVILEGES ON *.* TO 'app_user'@'%';
FLUSH PRIVILEGES;
