FROM alibaba-cloud-linux-3-registry.cn-hangzhou.cr.aliyuncs.com/alinux3/redis_optimized:20240221-6.2.7-2.3.0

COPY new_init_redis.sh /usr/local/bin/init_redis.sh
RUN chmod 777 /usr/local/bin/init_redis.sh
